##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-backgrounds
    - gcc
    - git
    - gtk3
    - intltool
    - libfakekey
    - libwnck3
    - make
    - mate-common
    - mate-panel
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-backgrounds
    - git
    - libdconf-dev
    - libfakekey-dev
    - libgtk-3-dev
    - libmate-panel-applet-dev
    - libwnck-3-dev
    - make
    - mate-common
    - yelp-tools

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-backgrounds.git
    - gcc
    - desktop-file-utils
    - git
    - gtk3-devel
    - libfakekey-devel
    - libwnck3-devel
    - make
    - mate-common
    - mate-panel-devel
    - redhat-rpm-config

  ubuntu:
    - git
    - libdconf-dev
    - libfakekey-dev
    - libgtk-3-dev
    - libmate-panel-applet-dev
    - libwnck-3-dev
    - make
    - mate-common
    - yelp-tools

variables:
  - CFLAGS="-Wall -Werror=format-security"

before_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     curl -Ls -o debian.sh https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/debian.sh
  -     bash ./debian.sh
  - fi

after_scripts:
  - make distcheck

releases:
  draft: false
  prerelease: false
  checksum: true
  file_glob: true
  files: mate-netbook-*.tar.xz
  github_release:
    tags: true
    overwrite: true
    base_version: 1.20.0
    notify_servers:
      - https://release.mate-desktop.org/release

